apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}tracker
spec:
  schedule: "0,30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          restartPolicy: Never
          initContainers:
          - name: check-db-ready
            image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
            imagePullPolicy: {{ .Values.pullPolicy }}
            resources:
              {{- toYaml .Values.tracker.cronjob.resources | nindent 14 }}
            env:
              - name: PGHOST
                value: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
              - name: PGPORT
                value: "{{ .Values.db.port }}"
            command: ['sh', '-c', 'until pg_isready; do echo waiting for database; sleep 2; done;']
          containers:
          - name: tracker
            image: {{ .Values.tracker.cronjob.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
            imagePullPolicy: {{ .Values.pullPolicy }}
            {{- if .Values.tracker.cacheDir }}
            env:
              - name: XDG_CACHE_HOME
                value: {{ .Values.tracker.cacheDir | quote }}
            {{- end }}
            volumeMounts:
            - name: tracker-config
              mountPath: {{ .Values.tracker.configDir | quote }}
              readOnly: true
            {{- if .Values.tracker.cacheDir }}
            - name: cache-dir
              mountPath: {{ .Values.tracker.cacheDir | quote }}
            {{- end }}
          volumes:
          - name: tracker-config
            secret:
              secretName: {{ include "chart.resourceNamePrefix" . }}tracker-config
          {{- if .Values.tracker.cacheDir }}
          - name: cache-dir
            emptyDir: {}
          {{- end }}
