nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
imageTag: latest
pullPolicy: IfNotPresent

log:
  level: info
  pretty: false

db:
  port: "5432"
  database: hub
  user: postgres
  password: postgres

hub:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  service:
    type: NodePort
    port: 80
  deploy:
    replicaCount: 1
    image:
      repository: artifacthub/hub
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  server:
    baseURL: ""
    shutdownTimeout: 10s
    basicAuth:
      enabled: false
      username: hub
      password: changeme
    cookie:
      hashKey: default-unsafe-key
      secure: false
    oauth:
      github:
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - read:user
          - user:email
      google:
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile
    limiter:
      enabled: false
    xffIndex: 0
  email:
    fromName: ""
    from: ""
    replyTo: ""
    smtp:
      host: ""
      port: 587
      username: ""
      password: ""
  analytics:
    gaTrackingID: ""

dbMigrator:
  job:
    image:
      repository: artifacthub/db-migrator
  loadSampleData: true

scanner:
  cronjob:
    image:
      repository: artifacthub/scanner
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  concurrency: 10
  trivyURL: http://trivy:8081

tracker:
  cronjob:
    image:
      repository: artifacthub/tracker
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  concurrency: 10
  repositoriesNames: []
  repositoriesKinds: []
  imageStore: pg
  bypassDigestCheck: false
  events:
    trackingErrors: false

trivy:
  deploy:
    image: aquasec/trivy:0.11.0
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  persistence:
    enabled: false
    size: 10Gi

# Values for postgresql chart dependency
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 12
  persistence:
    mountPath: /data
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: hub
  postgresqlDataDir: /data/pgdata
