nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
imageTag: ""
dynamicResourceNamePrefixEnabled: false
pullPolicy: IfNotPresent

log:
  level: info
  pretty: false

db:
  host: ""
  port: "5432"
  database: hub
  user: postgres
  password: postgres

dbMigrator:
  job:
    image:
      repository: artifacthub/db-migrator
  loadSampleData: true
  configDir: "/home/db-migrator/.cfg"

hub:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    rules: []
    tls: []
  service:
    type: NodePort
    port: 80
  deploy:
    readinessGates: []
    replicaCount: 1
    image:
      repository: artifacthub/hub
    resources: {}
  server:
    allowPrivateRepositories: false
    cacheDir: ""
    configDir: "/home/hub/.cfg"
    baseURL: ""
    shutdownTimeout: 10s
    basicAuth:
      enabled: false
      username: hub
      password: changeme
    cookie:
      hashKey: default-unsafe-key
      secure: false
    oauth:
      github:
        enabled: false
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - read:user
          - user:email
      google:
        enabled: false
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile
      oidc:
        enabled: false
        issuerURL: ""
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - openid
          - profile
          - email
    xffIndex: 0
  email:
    fromName: ""
    from: ""
    replyTo: ""
    smtp:
      host: ""
      port: 587
      username: ""
      password: ""
  analytics:
    gaTrackingID: ""

scanner:
  cronjob:
    image:
      repository: artifacthub/scanner
    resources: {}
  concurrency: 10
  trivyURL: http://trivy:8081
  cacheDir: ""
  configDir: "/home/scanner/.cfg"
  dockerUsername: ""
  dockerPassword: ""

tracker:
  cronjob:
    image:
      repository: artifacthub/tracker
    resources: {}
  cacheDir: ""
  configDir: "/home/tracker/.cfg"
  concurrency: 10
  repositoriesNames: []
  repositoriesKinds: []
  imageStore: pg
  bypassDigestCheck: false
  events:
    trackingErrors: false
  githubToken: ""

trivy:
  deploy:
    image: aquasec/trivy:0.15.0
    resources: {}
  persistence:
    enabled: false
    size: 10Gi

# Values for postgresql chart dependency
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 12
  persistence:
    mountPath: /data
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: hub
  postgresqlDataDir: /data/pgdata
