log:
  level: debug
  pretty: true
db:
  db:
  host: localhost
  port: "5432"
  database: hub
  user: postgres
tracker:
  concurrency: 10
  repositoriesNames: []
  repositoriesKinds: []
  bypassDigestCheck: false
